/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConnectFour */

#ifndef _Included_ConnectFour
#define _Included_ConnectFour
#ifdef __cplusplus
extern "C" {
#endif
#undef ConnectFour_FOCUS_TRAVERSABLE_UNKNOWN
#define ConnectFour_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef ConnectFour_FOCUS_TRAVERSABLE_DEFAULT
#define ConnectFour_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef ConnectFour_FOCUS_TRAVERSABLE_SET
#define ConnectFour_FOCUS_TRAVERSABLE_SET 2L
#undef ConnectFour_TOP_ALIGNMENT
#define ConnectFour_TOP_ALIGNMENT 0.0f
#undef ConnectFour_CENTER_ALIGNMENT
#define ConnectFour_CENTER_ALIGNMENT 0.5f
#undef ConnectFour_BOTTOM_ALIGNMENT
#define ConnectFour_BOTTOM_ALIGNMENT 1.0f
#undef ConnectFour_LEFT_ALIGNMENT
#define ConnectFour_LEFT_ALIGNMENT 0.0f
#undef ConnectFour_RIGHT_ALIGNMENT
#define ConnectFour_RIGHT_ALIGNMENT 1.0f
#undef ConnectFour_serialVersionUID
#define ConnectFour_serialVersionUID -7644114512714619750LL
#undef ConnectFour_serialVersionUID
#define ConnectFour_serialVersionUID 4613797578919906343LL
#undef ConnectFour_INCLUDE_SELF
#define ConnectFour_INCLUDE_SELF 1L
#undef ConnectFour_SEARCH_HEAVYWEIGHTS
#define ConnectFour_SEARCH_HEAVYWEIGHTS 1L
#undef ConnectFour_NOT_OBSCURED
#define ConnectFour_NOT_OBSCURED 0L
#undef ConnectFour_PARTIALLY_OBSCURED
#define ConnectFour_PARTIALLY_OBSCURED 1L
#undef ConnectFour_COMPLETELY_OBSCURED
#define ConnectFour_COMPLETELY_OBSCURED 2L
#undef ConnectFour_WHEN_FOCUSED
#define ConnectFour_WHEN_FOCUSED 0L
#undef ConnectFour_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define ConnectFour_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef ConnectFour_WHEN_IN_FOCUSED_WINDOW
#define ConnectFour_WHEN_IN_FOCUSED_WINDOW 2L
#undef ConnectFour_UNDEFINED_CONDITION
#define ConnectFour_UNDEFINED_CONDITION -1L
#undef ConnectFour_IS_DOUBLE_BUFFERED
#define ConnectFour_IS_DOUBLE_BUFFERED 0L
#undef ConnectFour_ANCESTOR_USING_BUFFER
#define ConnectFour_ANCESTOR_USING_BUFFER 1L
#undef ConnectFour_IS_PAINTING_TILE
#define ConnectFour_IS_PAINTING_TILE 2L
#undef ConnectFour_IS_OPAQUE
#define ConnectFour_IS_OPAQUE 3L
#undef ConnectFour_KEY_EVENTS_ENABLED
#define ConnectFour_KEY_EVENTS_ENABLED 4L
#undef ConnectFour_FOCUS_INPUTMAP_CREATED
#define ConnectFour_FOCUS_INPUTMAP_CREATED 5L
#undef ConnectFour_ANCESTOR_INPUTMAP_CREATED
#define ConnectFour_ANCESTOR_INPUTMAP_CREATED 6L
#undef ConnectFour_WIF_INPUTMAP_CREATED
#define ConnectFour_WIF_INPUTMAP_CREATED 7L
#undef ConnectFour_ACTIONMAP_CREATED
#define ConnectFour_ACTIONMAP_CREATED 8L
#undef ConnectFour_CREATED_DOUBLE_BUFFER
#define ConnectFour_CREATED_DOUBLE_BUFFER 9L
#undef ConnectFour_IS_PRINTING
#define ConnectFour_IS_PRINTING 11L
#undef ConnectFour_IS_PRINTING_ALL
#define ConnectFour_IS_PRINTING_ALL 12L
#undef ConnectFour_IS_REPAINTING
#define ConnectFour_IS_REPAINTING 13L
#undef ConnectFour_WRITE_OBJ_COUNTER_FIRST
#define ConnectFour_WRITE_OBJ_COUNTER_FIRST 14L
#undef ConnectFour_RESERVED_1
#define ConnectFour_RESERVED_1 15L
#undef ConnectFour_RESERVED_2
#define ConnectFour_RESERVED_2 16L
#undef ConnectFour_RESERVED_3
#define ConnectFour_RESERVED_3 17L
#undef ConnectFour_RESERVED_4
#define ConnectFour_RESERVED_4 18L
#undef ConnectFour_RESERVED_5
#define ConnectFour_RESERVED_5 19L
#undef ConnectFour_RESERVED_6
#define ConnectFour_RESERVED_6 20L
#undef ConnectFour_WRITE_OBJ_COUNTER_LAST
#define ConnectFour_WRITE_OBJ_COUNTER_LAST 21L
#undef ConnectFour_REQUEST_FOCUS_DISABLED
#define ConnectFour_REQUEST_FOCUS_DISABLED 22L
#undef ConnectFour_INHERITS_POPUP_MENU
#define ConnectFour_INHERITS_POPUP_MENU 23L
#undef ConnectFour_OPAQUE_SET
#define ConnectFour_OPAQUE_SET 24L
#undef ConnectFour_AUTOSCROLLS_SET
#define ConnectFour_AUTOSCROLLS_SET 25L
#undef ConnectFour_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define ConnectFour_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef ConnectFour_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define ConnectFour_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
#undef ConnectFour_ROWS
#define ConnectFour_ROWS 4L
#undef ConnectFour_COLS
#define ConnectFour_COLS 5L
#undef ConnectFour_CELL_SIZE
#define ConnectFour_CELL_SIZE 80L
#undef ConnectFour_CIRCLE_DIAMETER
#define ConnectFour_CIRCLE_DIAMETER 60L
#undef ConnectFour_PARKING_AREA_HEIGHT
#define ConnectFour_PARKING_AREA_HEIGHT 100L
/*
 * Class:     ConnectFour
 * Method:    getBoard
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_ConnectFour_getBoard
  (JNIEnv *, jobject);

/*
 * Class:     ConnectFour
 * Method:    setBoardCell
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ConnectFour_setBoardCell
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ConnectFour
 * Method:    checkWin
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ConnectFour_checkWin
  (JNIEnv *, jobject, jint);

/*
 * Class:     ConnectFour
 * Method:    startNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ConnectFour_startNew
  (JNIEnv *, jobject);

/*
 * Class:     ConnectFour
 * Method:    isRedTurn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ConnectFour_isRedTurn
  (JNIEnv *, jobject);

/*
 * Class:     ConnectFour
 * Method:    changeTurn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ConnectFour_changeTurn
  (JNIEnv *, jobject);

/*
 * Class:     ConnectFour
 * Method:    checkDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ConnectFour_checkDraw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
